mediapipe:
  pose:
    min_detection_confidence: 0.8
    min_tracking_confidence: 0.8

video_capture:
  device: 0
  flip: true
  show_landmarks: false

pose_estimation:
  curl_counter:
    min_angle: 20
    max_angle: 150
  squat_counter:
    min_angle: 130
    max_angle: 175

interface:
  window_name: AI Gym Tracker
  stats_bar:
    background_color:
      r: 0
      g: 0
      b: 0
    position_top: true
  start_pose_image_path: src/assets/human-body-pose-3d.png
  counter:
    font: FONT_HERSHEY_DUPLEX
    font_scale: 3
  double_counter:
    font: FONT_HERSHEY_DUPLEX
    font_scale: 2
  message:
    font: FONT_HERSHEY_SIMPLEX
    font_scale: 2
  title:
    font: FONT_HERSHEY_SIMPLEX
    font_scale: 3
  sets:
    font: FONT_HERSHEY_SIMPLEX
    font_scale: 2

logging:
  level: INFO

