mediapipe:
  pose:
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5

pose_estimation:
  curl_counter:
    min_angle: 30
    max_angle: 150

video_capture:
  device: 0
  flip: true
  show_landmarks: true

logging:
  level: INFO
